name: changelog

on:
  push:
    branches: [ developer ]

jobs:
  build:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1
        with:
          fetch-depth: 0

      - name: Generate Changelog
        uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.12'
      - run: python ~/work/moogles_intuition/moogles_intuition/.github/scripts/gen_changelog.py $$ 
